version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: boleto_app_campanha
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - pgsql
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: boleto_queue_campanha
    working_dir: /var/www
    command: php artisan queue:work --tries=3 --timeout=60
    volumes:
      - ./:/var/www
    depends_on:
      - pgsql
      - app
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: boleto_scheduler_campanha
    working_dir: /var/www
    command: php artisan schedule:work
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: boleto_nginx_campanha
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boleto.rule=Host(`boleto.campanha.localhost`)"
      - "traefik.http.services.boleto.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel
      - web

  pgsql:
    image: postgres:16
    container_name: boleto_pgsql_campanha
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
  web:
    external: true